apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-288405
  artifacts:
    - image: willycedric/shopping-backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: willycedric/shopping-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
